import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

@Component({ selector: 'app-contact', standalone: true, imports: [CommonModule, ReactiveFormsModule], template: `
<section class="contact" id="contact"><div class="contact-heading"><p class="eyebrow">Start a conversation</p><h2>Tell us what<br>you're <em>dreaming of.</em></h2><p>Have a site, a question, or just the beginning of an idea? We'd love to hear it.</p><div class="map-preview"><iframe title="Mcube Architects & Consultants location" src="https://www.google.com/maps?q=19.1899984%2C72.9755557&amp;z=17&amp;output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><a class="map-card" [href]="mapsUrl" target="_blank" rel="noopener noreferrer" aria-label="Open our studio location in Google Maps"><span class="map-pin">⌖</span><span><small>Get directions</small>{{ studioAddress }}</span><b>↗</b></a></div></div><form [formGroup]="form" (ngSubmit)="submit()" novalidate><label>Your name<input formControlName="name" placeholder="e.g. Ayesha Sharma"></label><label>Email address<input formControlName="email" type="email" placeholder="you@email.com"></label><label>I'm planning a<select formControlName="project"><option>Residential</option><option>Commercial</option><option>Hospitality</option><option>Interior renovation</option><option>Something else</option></select></label><label>Tell us a little about it<textarea formControlName="message" rows="3" placeholder="Where is it? What do you imagine?"></textarea></label><button class="submit" type="submit" [disabled]="status === 'sending'">{{ status === 'sending' ? 'Sending…' : 'Send your note ↗' }}</button><p class="form-message success" *ngIf="status === 'sent'">Thank you—your note is on its way.</p><p class="form-message error" *ngIf="status === 'error'">Email delivery needs configuration. See README for the one-time setup.</p></form></section>`, styleUrl: './app.component.scss' })
export class ContactComponent {
  private readonly fb = inject(FormBuilder);
  /** Replace this with the exact address you want clients to navigate to. */
  readonly studioAddress = "Prabhat Nagar, Shop No. G-02, Gajavakra CHS, behind GEI's Blossom School, Naupada, Thane, Maharashtra 400601";
  readonly mapsUrl = 'https://www.google.com/maps/place/Mcube+architects+%26+consultants/@19.1899984,72.9729808,17z/data=!3m1!4b1!4m6!3m5!1s0x3be7b9156a3955f1:0x5d050aca2dc1caa2!8m2!3d19.1899984!4d72.9755557!16s%2Fg%2F11ntpzjt94?entry=ttu&g_ep=EgoyMDI2MDgyNi4wIKXMDSoASAFQAw%3D%3D';
  status: 'idle' | 'sending' | 'sent' | 'error' = 'idle';
  form = this.fb.nonNullable.group({ name: ['', Validators.required], email: ['', [Validators.required, Validators.email]], project: ['Residential', Validators.required], message: ['', [Validators.required, Validators.minLength(12)]] });
  async submit() { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.status = 'sending'; const serviceId = 'YOUR_EMAILJS_SERVICE_ID', templateId = 'YOUR_EMAILJS_TEMPLATE_ID', publicKey = 'YOUR_EMAILJS_PUBLIC_KEY'; try { if (serviceId.startsWith('YOUR_')) throw new Error(); const response = await fetch('https://api.emailjs.com/api/v1.0/email/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ service_id: serviceId, template_id: templateId, user_id: publicKey, template_params: this.form.getRawValue() }) }); if (!response.ok) throw new Error(); this.status = 'sent'; this.form.reset({ name: '', email: '', project: 'Residential', message: '' }); } catch { this.status = 'error'; } }
}
