import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
type Project = { type: string; name: string; place: string; image: string; summary: string; facts: { label: string; value: string }[] };

@Component({ selector: 'app-work', standalone: true, imports: [CommonModule], styleUrl: './app.component.scss', template: `<section class="work" id="work"><div class="section-heading"><div><p class="eyebrow">Selected work</p><h2>Projects with purpose.</h2></div><span>{{ activeProject + 1 | number:'2.0' }}—{{ projects.length | number:'2.0' }}</span></div><div class="project-view" [style.background]="projects[activeProject].image"><div class="project-overlay"><p>{{ projects[activeProject].type }}</p><h3>{{ projects[activeProject].name }}</h3><span>{{ projects[activeProject].place }}</span></div></div><div class="project-tabs"><button *ngFor="let project of projects; let i = index" (click)="activeProject = i" [class.active]="activeProject === i"><span>{{ i + 1 | number:'2.0' }}</span>{{ project.name }}<b>↗</b></button></div><article class="project-info"><div><p class="eyebrow">Project overview</p><p class="project-summary">{{ projects[activeProject].summary }}</p></div><dl><div *ngFor="let fact of projects[activeProject].facts"><dt>{{ fact.label }}</dt><dd>{{ fact.value }}</dd></div></dl></article></section>` })
export class WorkComponent {
  activeProject = 0;
  projects: Project[] = [
    { type: 'High-rise residential development', name: 'Zidane Tower', place: 'Bhiwandi, Thane', image: "url('/assets/projects/zidane-tower.png') center/cover", summary: 'A premium residential development designed around modern architecture, functional planning and comfortable living, with emphasis on natural light, ventilation and a clean contemporary facade.', facts: [{label:'Project type',value:'Residential'},{label:'Scope',value:'Planning, 3D visualization & documentation'},{label:'Role',value:'Working architect (HK Design)'},{label:'Status',value:'Architectural design completed'}] },
    { type: 'Residential & commercial', name: 'Hammad Residency', place: 'Mumbra, Thane', image: "url('/assets/projects/hammad-residency.png') center/cover", summary: 'A well-planned mixed-use development that combines functional commercial spaces with comfortable residential living through a contemporary, carefully managed design approach.', facts: [{label:'Development',value:'G + 1 commercial + 6 residential floors'},{label:'Total area',value:'57,000 sq. ft.'},{label:'Project type',value:'Residential & commercial'},{label:'Scope',value:'Designed & managed by Mcube'}] },
    { type: 'Residential project', name: 'MK Empires', place: 'Bhiwandi, Maharashtra', image: "url('/assets/projects/mk-empires.png') center/cover", summary: 'A premium residential development focused on elevated everyday living, with a landscaped setting, dedicated parking and shared amenity spaces.', facts: [{label:'Project type',value:'Residential'},{label:'Key amenity',value:'Podium swimming pool'},{label:'Landscape',value:'Landscaped open spaces'},{label:'Parking',value:'Dedicated parking'}] },
    { type: 'Residential project', name: 'Raj Residency', place: 'Kongaon, Kalyan', image: "url('/assets/projects/raj-residency.png') center/cover", summary: 'A contemporary residential proposal blending modern architecture with efficient planning, generous openings and a strong urban presence.', facts: [{label:'Status',value:'Proposed'},{label:'Plot area',value:'871.00 sq. m'},{label:'Floors',value:'Ground + 12'},{label:'Typology',value:'Residential'}] },
    { type: 'Commercial project', name: 'Sainath Complex', place: 'Kaler, Bhiwandi', image: "url('/assets/projects/sanath-complex.png') center/cover", summary: 'A contemporary commercial development designed for modern retail and office spaces, with strong visibility, functional planning and efficient circulation.', facts: [{label:'Status',value:'Proposed'},{label:'Plot area',value:'1,250.00 sq. m'},{label:'Floors',value:'Ground + 5'},{label:'Typology',value:'Commercial'}] },
    { type: 'Residential project', name: 'Sangvi Delight', place: 'Bhiwandi', image: "url('/assets/projects/sanvi-delight.png') center/cover", summary: 'A contemporary residential building designed for comfortable living with efficient planning, ample natural light and a polished facade.', facts: [{label:'Status',value:'Proposed'},{label:'Plot area',value:'450.00 sq. m'},{label:'Floors',value:'Ground + 5'},{label:'Typology',value:'Residential'}] },
    { type: 'Residential project', name: 'Hasra Residency', place: 'Taloja Phase 2', image: "url('/assets/projects/hasra-residency.png') center/cover", summary: 'A thoughtfully planned residential development offering modern living spaces with premium design, quality construction and strong connectivity.', facts: [{label:'Homes',value:'1 & 2 BHK residences'},{label:'Floors',value:'Stilt + shop + residential floors'},{label:'Planning',value:'Vastu-compliant planning'},{label:'Amenities',value:'Parking, lobby & landscape area'}] },
    { type: 'Residential project', name: 'Supreme Palace', place: 'Mumbai', image: "url('/assets/projects/supreme-palace.png') center/cover", summary: 'A premium residential project combining classical architectural elements and modern aesthetics with thoughtfully planned layouts and quality finishes.', facts: [{label:'Status',value:'Proposed'},{label:'Plot area',value:'600.00 sq. m'},{label:'Floors',value:'Ground + 14'},{label:'Features',value:'Parking, children’s play area, CCTV & fire safety'}] },
    { type: 'Interior project', name: 'Residential Apartment', place: '2 BHK flat', image: "url('/assets/projects/interior-projects.png') center/cover", summary: 'A residential interior designed to blend functionality, comfort and elegance through thoughtful lighting, premium finishes, bespoke furniture and tailored storage.', facts: [{label:'Project type',value:'2 BHK interior design'},{label:'Design focus',value:'Functional layout & custom design'},{label:'Materials',value:'Carefully selected finishes & textures'},{label:'Outcome',value:'Comfort and everyday convenience'}] },
    { type: 'Interior project', name: 'Healthcare Interiors', place: 'First Care Hospital', image: "url('/assets/projects/interior-projects-2.png') center/cover", summary: 'Healthcare interiors that prioritise patient well-being, hygiene, smooth circulation and a calm environment for patients, visitors and staff.', facts: [{label:'Design focus',value:'Patient comfort & efficient layout'},{label:'Safety',value:'Easy-to-clean antimicrobial materials'},{label:'Planning',value:'Seamless staff and patient flow'},{label:'Approach',value:'Sustainable lighting & ventilation'}] }
  ];
}
